// <auto-generated />
namespace MyShop.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Intergate_Indentity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Intergate_Indentity));
        
        string IMigrationMetadata.Id
        {
            get { return "201607070853311_Intergate_Indentity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
